# Generated by Django 4.2.16 on 2024-11-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='periodo',
            field=models.CharField(default='semanal', max_length=100),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero_sala',
            field=models.CharField(max_length=100),
        ),
    ]
