# Generated by Django 5.1 on 2024-11-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='consultas_por_dia',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='horario_inicio',
        ),
        migrations.RemoveField(
            model_name='psicologo',
            name='tempo_consulta',
        ),
    ]
