# Generated by Django 5.1 on 2024-11-08 17:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaPsico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=100)),
                ('hora', models.TimeField()),
                ('livre_ocupado', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='paciente',
            new_name='Paciente',
        ),
        migrations.RenameField(
            model_name='disponibilidade',
            old_name='hora_fim',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='disponibilidade',
            name='data',
        ),
        migrations.RemoveField(
            model_name='disponibilidade',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='dia_semana',
            field=models.CharField(default=datetime.datetime(2024, 11, 8, 17, 21, 8, 58894, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='livre_ocupado',
            field=models.CharField(default=datetime.datetime(2024, 11, 8, 17, 21, 18, 226199, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psicodisponibilidade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='psicodisponibilidade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.psicologo'),
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together={('psicologo', 'horario')},
        ),
        migrations.AlterField(
            model_name='psicodisponibilidade',
            name='disponibilidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.agendapsico'),
        ),
    ]
