# Generated by Django 5.1.1 on 2024-11-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_psicologa_consultas_por_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologa',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologa',
            name='senha',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
