# Generated by Django 4.2.16 on 2024-11-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_paciente_periodo_alter_sala_numero_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
