# Generated by Django 4.2.16 on 2024-10-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_usuario_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id_unidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome_unidade', models.CharField(max_length=100)),
                ('endereco_unidade', models.CharField(max_length=100)),
                ('CEP_unidade', models.IntegerField()),
            ],
        ),
    ]
