# Generated by Django 4.2.16 on 2024-11-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_psicologo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='Paciente',
            new_name='paciente',
        ),
    ]
