# Generated by Django 5.1.1 on 2024-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_consulta_unique_together_consulta_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.TimeField(),
        ),
    ]
