# Generated by Django 5.1.1 on 2024-11-07 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_psicologa_email_psicologa_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='psicologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.psicologa'),
        ),
        migrations.RemoveField(
            model_name='confirmacaoconsulta',
            name='horario_fim',
        ),
        migrations.RemoveField(
            model_name='confirmacaoconsulta',
            name='sala_atendimento',
        ),
        migrations.RemoveField(
            model_name='confirmacaoconsulta',
            name='user',
        ),
        migrations.AddField(
            model_name='confirmacaoconsulta',
            name='psicologa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.psicologa'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Psicologo',
        ),
    ]
