# Generated by Django 5.1 on 2024-11-06 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_consulta_unique_together_and_more'),
        ('home', '0004_rename_paciente_consulta_paciente'),
    ]

    operations = [
    ]
