# Generated by Django 5.1.1 on 2024-11-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_consulta_psicologo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='dia_semana',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
