# Generated by Django 5.1.1 on 2024-11-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_consulta_psicologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='quinzenal',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='semanal',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
