# Generated by Django 3.2.6 on 2024-10-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_confirmacaoconsulta_disponibilidade_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditProfileForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
