# Generated by Django 4.2.16 on 2024-11-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_consulta_quinzenal_consulta_semanal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pendente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_acertado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_pacientes', models.IntegerField()),
                ('desistencias_atendidos', models.IntegerField()),
                ('qtd_marcacoes', models.IntegerField()),
                ('desistencias_novos', models.IntegerField()),
            ],
        ),
    ]
