# Generated by Django 5.1.1 on 2024-11-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_repeticao_consulta_quinzenal_consulta_semanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.TimeField(),
        ),
    ]
