# Generated by Django 3.2.6 on 2024-10-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_editprofileform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditProfileForm',
        ),
    ]
