# Generated by Django 5.1.1 on 2024-10-26 17:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_editprofileform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacaoconsulta',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmacaoconsulta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.IntegerField(),
        ),
    ]
