# Generated by Django 5.1.1 on 2024-11-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_consulta_horario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together=set(),
        ),
    ]
