# Generated by Django 3.2.6 on 2024-11-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_financeiro_psicologa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_total',
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='desistencias_atendidos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='desistencias_novos',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='qtd_marcacoes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='qtd_pacientes',
            field=models.PositiveIntegerField(),
        ),
    ]
