# Generated by Django 4.2.16 on 2024-11-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20241113_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
