# Generated by Django 4.2.16 on 2024-10-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_confirmacaoconsulta_id_alter_consulta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='cor_sala',
            field=models.CharField(choices=[('red', 'Vermelho'), ('green', 'Verde'), ('blue', 'Azul'), ('black', 'Preto'), ('white', 'Branco'), ('gray', 'Cinza'), ('yellow', 'Amarelo'), ('cyan', 'Ciano'), ('magenta', 'Magenta')], default='white', max_length=20),
        ),
    ]
