# Generated by Django 5.1.1 on 2024-11-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_financeiro_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacaoconsulta',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
