# Generated by Django 5.1.1 on 2024-11-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_confirmacaoconsulta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicodisponibilidade',
            name='disponibilidade',
        ),
        migrations.DeleteModel(
            name='Disponibilidade',
        ),
        migrations.RemoveField(
            model_name='psicodisponibilidade',
            name='user',
        ),
        migrations.RenameField(
            model_name='confirmacaoconsulta',
            old_name='status',
            new_name='dia_semana',
        ),
        migrations.RenameField(
            model_name='confirmacaoconsulta',
            old_name='psicologo',
            new_name='psicologa',
        ),
        migrations.AddField(
            model_name='confirmacaoconsulta',
            name='horario_inicio',
            field=models.TimeField(default="10:20"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='confirmacaoconsulta',
            name='periodo_atendimento',
            field=models.CharField(default="semanal", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confirmacaoconsulta',
            name='data',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='AgendaPsico',
        ),
        migrations.DeleteModel(
            name='PsicoDisponibilidade',
        ),
        migrations.DeleteModel(
            name='Psicologo',
        ),
    ]
