# Generated by Django 4.2.16 on 2024-10-29 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_sala_cor_sala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='id',
            new_name='id_consulta',
        ),
    ]
