# Generated by Django 5.1.1 on 2024-11-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_psicodisponibilidade_disponibilidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadePsico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='repeticao',
        ),
    ]
