# Generated by Django 4.2.16 on 2024-10-30 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_id_consulta_id_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmacaoconsulta',
            old_name='id',
            new_name='id_consulta',
        ),
    ]
