# Generated by Django 4.2.16 on 2024-10-30 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_id_confirmacaoconsulta_id_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacaoconsulta',
            name='confirmacao',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
