# Generated by Django 5.1.1 on 2024-11-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_especialidadepsico_remove_consulta_repeticao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='rg',
        ),
        migrations.AddField(
            model_name='paciente',
            name='nome_responsavel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_atendimento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='valor',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologa',
            name='abordagem',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='psicologa',
            name='especializacao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='idade',
            field=models.CharField(max_length=100),
        ),
    ]
