# Generated by Django 4.2.16 on 2024-10-30 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_confirmacaoconsulta_confirmacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmacaoconsulta',
            name='sala_atendimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.sala'),
            preserve_default=False,
        ),
    ]
