# Generated by Django 5.1.1 on 2024-11-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_paciente_cpf_remove_paciente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
