# Generated by Django 4.2.16 on 2024-11-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_confirmacaoconsulta_sala_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='periodo',
            field=models.CharField(default='semanal', max_length=100),
        ),
    ]
