# Generated by Django 5.1.1 on 2024-11-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_paciente_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publico', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='psicologa',
            name='especializacao',
        ),
        migrations.AddField(
            model_name='especialidadepsico',
            name='psico',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='home.psicologa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialidadepsico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='especialidadepsico',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.especialidade'),
        ),
        migrations.CreateModel(
            name='publicoPsico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.psicologa')),
                ('publico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.publico')),
            ],
        ),
    ]
