# Generated by Django 4.2.16 on 2024-11-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_paciente_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cor_psicologa',
            field=models.CharField(choices=[('red', 'Vermelho'), ('green', 'Verde'), ('blue', 'Azul'), ('black', 'Preto'), ('white', 'Branco'), ('gray', 'Cinza'), ('yellow', 'Amarelo'), ('cyan', 'Ciano'), ('magenta', 'Magenta')], default='black', max_length=20),
        ),
    ]
