# Generated by Django 5.1.1 on 2024-11-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_especialidade_publico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(blank=True, max_length=32, null=True)),
                ('periodo_atendimento', models.CharField(blank=True, max_length=32, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('presenca', models.CharField(blank=True, max_length=32, null=True)),
                ('forma', models.CharField(blank=True, max_length=32, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=32, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
                ('psicologa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.psicologa')),
            ],
        ),
    ]
