# Generated by Django 4.2.16 on 2024-11-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_usuario_cor_psicologa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cor_psicologa',
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero_sala',
            field=models.CharField(max_length=100),
        ),
    ]
