# Generated by Django 5.1.1 on 2024-11-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_financeiro2_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro2',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
