# Generated by Django 5.1.1 on 2024-12-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_financeiro2_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro2',
            name='semana',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
