# Generated by Django 5.1.1 on 2024-12-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_financeiro2_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='CEP_unidade',
            field=models.CharField(max_length=100),
        ),
    ]
