# Generated by Django 5.1.1 on 2024-12-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_unidade_cep_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='cor_sala',
            field=models.CharField(max_length=16),
        ),
    ]
