# Generated by Django 5.1.1 on 2024-12-10 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_sala_cor_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='tipo_atendimento',
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=100)),
                ('hora', models.TimeField()),
                ('psicologa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.psicologa')),
            ],
        ),
    ]
