# Generated by Django 5.1.1 on 2024-12-17 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_paciente_tipo_atendimento_disponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadePsico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.psicologa')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.unidade')),
            ],
        ),
    ]
