# Generated by Django 5.1.1 on 2025-01-14 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_paciente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='Paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.paciente'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='quinzenal',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='semanal',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
