# Generated by Django 5.1.1 on 2025-01-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_consulta_paciente_alter_consulta_quinzenal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='psicologo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.psicologa'),
        ),
    ]
