# Generated by Django 5.1.1 on 2025-01-30 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_consulta_psicologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Consulta_Online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('dia_semana', models.CharField(max_length=100)),
                ('semanal', models.CharField(max_length=32, null=True)),
                ('quinzenal', models.CharField(max_length=32, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('Paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.paciente')),
                ('psicologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.psicologa')),
            ],
        ),
    ]
