# Generated by Django 5.1.1 on 2025-01-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_consulta_ultima_atualizacao_consulta_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
    ]
