# Generated by Django 5.1.1 on 2025-01-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_paciente_deletado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='ultima_atualizacao',
            field=models.DateField(auto_now=True),
        ),
    ]
