# Generated by Django 5.1.1 on 2025-01-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_consulta_ultima_atualizacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='ultima_atualizacao',
        ),
        migrations.AddField(
            model_name='psicologa',
            name='ultima_atualizacao_agenda',
            field=models.DateField(auto_now=True),
        ),
    ]
