# Generated by Django 5.1.1 on 2025-02-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_consulta_ultima_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro2',
            name='modalidade',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
