# Generated by Django 5.1.1 on 2025-04-04 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_despesas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeiro',
            old_name='valor_total',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='desistencias_atendidos',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='desistencias_novos',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='qtd_marcacoes',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='qtd_pacientes',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_acertado',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_pendente',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='valor_previsto',
        ),
        migrations.AddField(
            model_name='financeiro',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='dia_semana',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='forma',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='modalidade',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='observacoes',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='paciente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financeiro',
            name='periodo_atendimento',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='presenca',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='semana',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financeiro',
            name='valor_pagamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='psicologa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.psicologa'),
        ),
        migrations.DeleteModel(
            name='Financeiro2',
        ),
    ]
