# Generated by Django 5.1.1 on 2025-04-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rename_valor_total_financeiro_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='bloqueada',
            field=models.BooleanField(default=False),
        ),
    ]
