# Generated by Django 5.1.1 on 2025-05-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_psicoconfirmarconsulta_confirmacao_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologa',
            name='cor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='psicologa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rg',
            field=models.CharField(max_length=100),
        ),
    ]
