# Generated by Django 5.1.1 on 2025-05-21 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_psicologa_cor_alter_psicologa_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='horario_fim',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='horario_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
