# Generated by Django 5.1.1 on 2025-06-30 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_sala_horario_fim_sala_horario_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='metodo',
            field=models.CharField(default='livre', max_length=20),
        ),
    ]
