# Generated by Django 5.1.1 on 2025-06-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_consulta_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='metodo',
            field=models.CharField(choices=[('livre', 'Livre'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('fechado', 'Fechado')], default='livre', help_text='Método de agendamento para este horário', max_length=20),
        ),
    ]
