# Generated by Django 5.1.1 on 2025-06-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_consulta_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='metodo',
            field=models.CharField(choices=[('padrao', 'Padrão'), ('livre', 'Livre'), ('fechado', 'Fechado')], default='livre', help_text='Método de agendamento para este horário', max_length=20),
        ),
    ]
