# Generated by Django 5.1.1 on 2025-07-09 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_consulta_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_deletado_psico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='data_inspec_admin',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='motivo_deletado_psico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='obs_admin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='metodo',
            field=models.CharField(choices=[('padrao', 'Padrão'), ('livre', 'Livre'), ('fechado', 'Fechado')], default='padrao', help_text='Método de agendamento para este horário', max_length=20),
        ),
    ]
